# Generated by Django 3.2.5 on 2021-10-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance',
            name='claim_form',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='price',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='register_form',
        ),
        migrations.AlterField(
            model_name='insurance',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
