# Generated by Django 3.2.5 on 2021-10-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_auto_20211007_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='claim_form',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='register_form',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='description',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
