# Generated by Django 3.2.5 on 2021-11-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_auto_20211007_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('claim_form', models.JSONField(null=True)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='claim_form',
        ),
        migrations.AddField(
            model_name='insurance',
            name='coverage',
            field=models.ManyToManyField(blank=True, related_name='coverage', to='insurance.Coverage'),
        ),
    ]
