# Generated by Django 3.2.5 on 2021-12-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_auto_20211114_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverage',
            name='capacity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='insurance',
            name='coverage',
            field=models.ManyToManyField(related_name='coverage', to='insurance.Coverage'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='description',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='price',
            field=models.IntegerField(),
        ),
    ]
