# Generated by Django 3.2.5 on 2021-10-07 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted_by_company', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_code', models.IntegerField(blank=True, null=True)),
                ('register_form', models.JSONField()),
                ('insurance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance.insurance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
