# Generated by Django 3.2.5 on 2021-10-07 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insuranceconnector',
            name='register_form',
        ),
    ]
