# Generated by Django 3.2.5 on 2021-11-02 18:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[(1, 'Company'), (2, 'Vendor'), (3, 'SuperHolder'), (4, 'Holder'), (5, 'Insured')], max_length=11),
        ),
    ]
