# Generated by Django 3.2.5 on 2021-11-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_auto_20211102_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.IntegerField(choices=[(1, 'Company'), (2, 'Vendor'), (3, 'SuperHolder'), (4, 'Holder'), (5, 'Insured')]),
        ),
    ]
