# Generated by Django 3.2.5 on 2021-11-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0004_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[(1, 'Company'), (2, 'Vendor'), (3, 'Superholder'), (4, 'Holder'), (5, 'Insured')], max_length=11),
        ),
    ]
