# Generated by Django 3.2.5 on 2021-11-12 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insurance', '0004_auto_20211112_1657'),
        ('ticket', '0003_claim_reviewer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='coverage',
        ),
        migrations.AddField(
            model_name='claim',
            name='coverage',
            field=models.ManyToManyField(blank=True, related_name='claim_coverage', to='insurance.Coverage'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claim_reviewer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ReviewerTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
