# Generated by Django 3.2.5 on 2021-11-13 10:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_rename_data_reviewertimeline_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewertimeline',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
