# Generated by Django 3.2.5 on 2021-12-13 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_insuranceconnector_claim'),
        ('insurance', '0006_auto_20211213_1726'),
        ('ticket', '0007_alter_reviewertimeline_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='coverage',
        ),
        migrations.AddField(
            model_name='claim',
            name='coverage',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='claim_coverage', to='insurance.coverage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='claim',
            name='insurance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='claims_insurance', to='payment.insuranceconnector'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('Opened', 'Opened'), ('Reopened', 'Reopened'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Opened', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Opened', 'Opened'), ('Reopened', 'Reopened'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Opened', max_length=10),
        ),
    ]
