# Generated by Django 3.2.5 on 2021-10-07 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insured', '0002_auto_20211007_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insured',
            name='bank_account_number',
        ),
        migrations.RemoveField(
            model_name='insured',
            name='insurance',
        ),
    ]
