# Generated by Django 3.2.5 on 2021-11-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insured', '0003_auto_20211007_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='insured',
            name='age',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='insured',
            name='illness',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
